// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: public_vote.proto

package voting

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PublicVoteService_Create_FullMethodName       = "/voting.PublicVoteService/Create"
	PublicVoteService_CreateVotes_FullMethodName  = "/voting.PublicVoteService/CreateVotes"
	PublicVoteService_GetById_FullMethodName      = "/voting.PublicVoteService/GetById"
	PublicVoteService_GetByVotesId_FullMethodName = "/voting.PublicVoteService/GetByVotesId"
	PublicVoteService_GetAll_FullMethodName       = "/voting.PublicVoteService/GetAll"
	PublicVoteService_GetAllVotes_FullMethodName  = "/voting.PublicVoteService/GetAllVotes"
	PublicVoteService_Update_FullMethodName       = "/voting.PublicVoteService/Update"
	PublicVoteService_UpdateVotes_FullMethodName  = "/voting.PublicVoteService/UpdateVotes"
	PublicVoteService_Delete_FullMethodName       = "/voting.PublicVoteService/Delete"
)

// PublicVoteServiceClient is the client API for PublicVoteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PublicVoteServiceClient interface {
	Create(ctx context.Context, in *CreatePublicVoteReq, opts ...grpc.CallOption) (*Void, error)
	CreateVotes(ctx context.Context, in *CreateVoteReq, opts ...grpc.CallOption) (*Void, error)
	GetById(ctx context.Context, in *ById, opts ...grpc.CallOption) (*GetPublicVoteRes, error)
	GetByVotesId(ctx context.Context, in *ById, opts ...grpc.CallOption) (*GetVotesRes, error)
	GetAll(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*GetAllPublicVoteRes, error)
	GetAllVotes(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*GetAllVotesRes, error)
	Update(ctx context.Context, in *GetPublicVoteRes, opts ...grpc.CallOption) (*Void, error)
	UpdateVotes(ctx context.Context, in *GetVotesRes, opts ...grpc.CallOption) (*Void, error)
	Delete(ctx context.Context, in *ById, opts ...grpc.CallOption) (*Void, error)
}

type publicVoteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPublicVoteServiceClient(cc grpc.ClientConnInterface) PublicVoteServiceClient {
	return &publicVoteServiceClient{cc}
}

func (c *publicVoteServiceClient) Create(ctx context.Context, in *CreatePublicVoteReq, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, PublicVoteService_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicVoteServiceClient) CreateVotes(ctx context.Context, in *CreateVoteReq, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, PublicVoteService_CreateVotes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicVoteServiceClient) GetById(ctx context.Context, in *ById, opts ...grpc.CallOption) (*GetPublicVoteRes, error) {
	out := new(GetPublicVoteRes)
	err := c.cc.Invoke(ctx, PublicVoteService_GetById_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicVoteServiceClient) GetByVotesId(ctx context.Context, in *ById, opts ...grpc.CallOption) (*GetVotesRes, error) {
	out := new(GetVotesRes)
	err := c.cc.Invoke(ctx, PublicVoteService_GetByVotesId_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicVoteServiceClient) GetAll(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*GetAllPublicVoteRes, error) {
	out := new(GetAllPublicVoteRes)
	err := c.cc.Invoke(ctx, PublicVoteService_GetAll_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicVoteServiceClient) GetAllVotes(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*GetAllVotesRes, error) {
	out := new(GetAllVotesRes)
	err := c.cc.Invoke(ctx, PublicVoteService_GetAllVotes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicVoteServiceClient) Update(ctx context.Context, in *GetPublicVoteRes, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, PublicVoteService_Update_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicVoteServiceClient) UpdateVotes(ctx context.Context, in *GetVotesRes, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, PublicVoteService_UpdateVotes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicVoteServiceClient) Delete(ctx context.Context, in *ById, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, PublicVoteService_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PublicVoteServiceServer is the server API for PublicVoteService service.
// All implementations must embed UnimplementedPublicVoteServiceServer
// for forward compatibility
type PublicVoteServiceServer interface {
	Create(context.Context, *CreatePublicVoteReq) (*Void, error)
	CreateVotes(context.Context, *CreateVoteReq) (*Void, error)
	GetById(context.Context, *ById) (*GetPublicVoteRes, error)
	GetByVotesId(context.Context, *ById) (*GetVotesRes, error)
	GetAll(context.Context, *Filter) (*GetAllPublicVoteRes, error)
	GetAllVotes(context.Context, *Filter) (*GetAllVotesRes, error)
	Update(context.Context, *GetPublicVoteRes) (*Void, error)
	UpdateVotes(context.Context, *GetVotesRes) (*Void, error)
	Delete(context.Context, *ById) (*Void, error)
	mustEmbedUnimplementedPublicVoteServiceServer()
}

// UnimplementedPublicVoteServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPublicVoteServiceServer struct {
}

func (UnimplementedPublicVoteServiceServer) Create(context.Context, *CreatePublicVoteReq) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedPublicVoteServiceServer) CreateVotes(context.Context, *CreateVoteReq) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVotes not implemented")
}
func (UnimplementedPublicVoteServiceServer) GetById(context.Context, *ById) (*GetPublicVoteRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetById not implemented")
}
func (UnimplementedPublicVoteServiceServer) GetByVotesId(context.Context, *ById) (*GetVotesRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByVotesId not implemented")
}
func (UnimplementedPublicVoteServiceServer) GetAll(context.Context, *Filter) (*GetAllPublicVoteRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedPublicVoteServiceServer) GetAllVotes(context.Context, *Filter) (*GetAllVotesRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllVotes not implemented")
}
func (UnimplementedPublicVoteServiceServer) Update(context.Context, *GetPublicVoteRes) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedPublicVoteServiceServer) UpdateVotes(context.Context, *GetVotesRes) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateVotes not implemented")
}
func (UnimplementedPublicVoteServiceServer) Delete(context.Context, *ById) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedPublicVoteServiceServer) mustEmbedUnimplementedPublicVoteServiceServer() {}

// UnsafePublicVoteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PublicVoteServiceServer will
// result in compilation errors.
type UnsafePublicVoteServiceServer interface {
	mustEmbedUnimplementedPublicVoteServiceServer()
}

func RegisterPublicVoteServiceServer(s grpc.ServiceRegistrar, srv PublicVoteServiceServer) {
	s.RegisterService(&PublicVoteService_ServiceDesc, srv)
}

func _PublicVoteService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePublicVoteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicVoteServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicVoteService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicVoteServiceServer).Create(ctx, req.(*CreatePublicVoteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicVoteService_CreateVotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVoteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicVoteServiceServer).CreateVotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicVoteService_CreateVotes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicVoteServiceServer).CreateVotes(ctx, req.(*CreateVoteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicVoteService_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicVoteServiceServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicVoteService_GetById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicVoteServiceServer).GetById(ctx, req.(*ById))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicVoteService_GetByVotesId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicVoteServiceServer).GetByVotesId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicVoteService_GetByVotesId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicVoteServiceServer).GetByVotesId(ctx, req.(*ById))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicVoteService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Filter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicVoteServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicVoteService_GetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicVoteServiceServer).GetAll(ctx, req.(*Filter))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicVoteService_GetAllVotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Filter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicVoteServiceServer).GetAllVotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicVoteService_GetAllVotes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicVoteServiceServer).GetAllVotes(ctx, req.(*Filter))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicVoteService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublicVoteRes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicVoteServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicVoteService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicVoteServiceServer).Update(ctx, req.(*GetPublicVoteRes))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicVoteService_UpdateVotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVotesRes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicVoteServiceServer).UpdateVotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicVoteService_UpdateVotes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicVoteServiceServer).UpdateVotes(ctx, req.(*GetVotesRes))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicVoteService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicVoteServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicVoteService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicVoteServiceServer).Delete(ctx, req.(*ById))
	}
	return interceptor(ctx, in, info, handler)
}

// PublicVoteService_ServiceDesc is the grpc.ServiceDesc for PublicVoteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PublicVoteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "voting.PublicVoteService",
	HandlerType: (*PublicVoteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _PublicVoteService_Create_Handler,
		},
		{
			MethodName: "CreateVotes",
			Handler:    _PublicVoteService_CreateVotes_Handler,
		},
		{
			MethodName: "GetById",
			Handler:    _PublicVoteService_GetById_Handler,
		},
		{
			MethodName: "GetByVotesId",
			Handler:    _PublicVoteService_GetByVotesId_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _PublicVoteService_GetAll_Handler,
		},
		{
			MethodName: "GetAllVotes",
			Handler:    _PublicVoteService_GetAllVotes_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _PublicVoteService_Update_Handler,
		},
		{
			MethodName: "UpdateVotes",
			Handler:    _PublicVoteService_UpdateVotes_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _PublicVoteService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "public_vote.proto",
}
