// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/election/create": {
            "post": {
                "description": "Endpoint for creating a new election",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Election"
                ],
                "summary": "Create a new election",
                "parameters": [
                    {
                        "description": "Election creation request payload",
                        "name": "election",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/voting.CreateElectionReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully created election",
                        "schema": {
                            "$ref": "#/definitions/voting.Void"
                        }
                    },
                    "400": {
                        "description": "Invalid request payload",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Failed to create election",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/election/getall": {
            "get": {
                "description": "Endpoint for getting all elections",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Election"
                ],
                "summary": "Get All Elections",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully getted elections",
                        "schema": {
                            "$ref": "#/definitions/voting.GetAllElectionRes"
                        }
                    },
                    "400": {
                        "description": "Invalid request payload",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Failed to get elections",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/election/getbyid": {
            "get": {
                "description": "Endpoint for getting election",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Election"
                ],
                "summary": "Get Election",
                "parameters": [
                    {
                        "type": "string",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully getted election",
                        "schema": {
                            "$ref": "#/definitions/voting.GetElectionRes"
                        }
                    },
                    "400": {
                        "description": "Invalid request payload",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Failed to get election",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/election/update": {
            "put": {
                "description": "Endpoint for updating election",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Election"
                ],
                "summary": "Update election",
                "operationId": "update_election",
                "parameters": [
                    {
                        "description": "Election updaing request payload",
                        "name": "election",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/voting.GetElectionRes"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully updated election",
                        "schema": {
                            "$ref": "#/definitions/voting.Void"
                        }
                    },
                    "400": {
                        "description": "Invalid request payload",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Failed to update election",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "voting.CreateElectionReq": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "voting.GetAllElectionRes": {
            "type": "object",
            "properties": {
                "Elections": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/voting.GetElectionRes"
                    }
                }
            }
        },
        "voting.GetElectionRes": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "voting.Void": {
            "type": "object"
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "role",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Online Voting System Swagger UI",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
